In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install tensorflow-gpu
!pip install tensorlayer

In [ ]:
%cd /content/drive/My Drive/Project_Testing

/content/drive/My Drive/Project_Testing


In [ ]:
!pwd

# **Fresh Training : MIFFGAN**

In [ ]:
!python main.py --mode=1 --gan_train --gen_model=6 --dis_model=2 --init_epoch=50 --total_epoch=100 --batch_size=10 --save_interval=5

# **Resume Training: MIFFGAN (Initial+Adverserial)**

In [ ]:
!python main.py --mode=1 --gan_train --load_weights --gan_init --gen_model=6 --dis_model=2 --model_epoch=50 --init_epoch=0 --total_epoch=100 --batch_size=8 --save_interval=1

# **Resume Training: MIFFGAN (Adverserial)**

In [ ]:
!python main.py --mode=1 --load_weights --gan_train --gen_model=6 --dis_model=2 --model_epoch=107 --total_epoch=2 --batch_size=8 --save_interval=1 --dir_train_in='Training'

2020-02-23 18:55:17.057761: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:55:17.057875: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:55:17.057894: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
I0223 18:55:18.530813 140076675999616 tl_logging.py:99] Input  _inputlayer_1: (None, 128, 128, 1)
2020-02-23 18:55:18.631614: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_grow

# **Validation: MIFFGAN**

In [ ]:
!python main.py --mode=2 --gan_train --gen_model=6 --model_epoch=107 --batch_size=8 --dir_val_in='Training'

# **Evaluation: MIFFGAN**

In [ ]:
!python main.py --mode=3 --gan_train --gen_model=4 --model_epoch=80

# **.........................................................MIFF.............................................................**

# **Fresh Training : MIFF**

In [ ]:
!python main.py --mode=1 --gen_model=7 --total_epoch=10 --batch_size=25 --save_interval=10 --dir_train_in='Training_inputs'

# **Resume Training: MIFF**

In [ ]:
!python main.py --mode=1 -load_weights --gen_model=6 --model_epoch=107 --total_epoch=2 --batch_size=8 --save_interval=2 --dir_train_in='Training'

# **Validation: MIFF**

In [ ]:
!python main.py --mode=2 --gen_model=4 --model_epoch=84 --batch_size=8 --dir_val_in='Training'

# **Evaluation: MIFF**

In [ ]:
!python main.py --mode=3 --gen_model=2 --model_epoch=5

# **.........................................................UTILITIES.............................................................**

# **Refresh Folder**

In [ ]:
!python utils.py refresh_folder '/content/drive/My Drive/Project_Testing/Training'

2020-02-23 18:04:19.707615: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:04:19.707780: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:04:19.707805: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/content/drive/My Drive/Project_Testing/Training refreshed!


# **Remove File**

In [ ]:
!python utils.py remove_file <file_path>

# **Copy Files**

In [ ]:
!python utils.py copy_images 'Training_GRAY256'\ 'Training'\ 1\ 8

2020-02-23 18:04:57.981530: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:04:57.981765: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-23 18:04:57.981807: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Copy successful!


# **New Model Check**

In [ ]:
!python model_list.py G 7

2020-02-19 11:13:33.606548: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 11:13:33.606630: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 11:13:33.606643: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-02-19 11:13:34.902299: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config valu

In [ ]:
import numpy as np
x=np.array([[[1,2],[4,1]],[[3,1],[4,3]],[[2,4],[1,2]]])
np.amax(x)

4

In [ ]:
import numpy
with open('models/stats_gen_5.npy', 'rb') as f:
                stats=numpy.load(f)
                print(stats)

[[-2.33872414  0.46629441 21.        ]
 [ 0.43167686  0.44520438 22.        ]
 [ 1.63023949  0.48049825 23.        ]
 [ 0.11074638  0.42495245 24.        ]
 [ 1.78051376  0.45892635 25.        ]
 [ 0.11773491  0.31772846 26.        ]
 [ 2.13122749  0.41685754 27.        ]
 [-2.56907463  0.40616131 28.        ]]


In [ ]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
#xmax, xmin = x.max(), x.min()
#x = (x - xmin)/(xmax - xmin)
#print("After normalization:")
#print(x)
print(x * 255) 
print((x * 255).round())
x = (x * 255).round().astype(np.uint8)
print(x)

Original Array:
[[0.81267766 0.07405017 0.88373317]
 [0.47183311 0.18863056 0.16513072]
 [0.01114131 0.75185364 0.30919395]]
[[207.2328041   18.8827928  225.35195943]
 [120.31744232  48.10079381  42.10833267]
 [  2.84103293 191.72267793  78.84445634]]
[[207.  19. 225.]
 [120.  48.  42.]
 [  3. 192.  79.]]
[[207  19 225]
 [120  48  42]
 [  3 192  79]]


In [ ]:
!python utils.py get_validation_data 'Valid'

2020-02-19 08:13:19.161860: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 08:13:19.162018: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 08:13:19.162039: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-02-19 08:13:20.334451: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config valu

In [ ]:
!python utils.py get_validation_data 'Valid'

2020-02-19 08:25:47.571258: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 08:25:47.571351: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-02-19 08:25:47.571366: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-02-19 08:25:48.687567: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config valu